<?php

namespace AppBundle\Repository;

/**
 * CoreRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CoreRepository extends \Doctrine\ORM\EntityRepository
{
}
