<?php

namespace AppBundle\Repository;

/**
 * requestInfoCoreRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class requestInfoCoreRepository extends \Doctrine\ORM\EntityRepository
{
}
