app:
    resource: '@AppBundle/Controller/'
    type: annotation

#homepage:
#    path:   /login

root:
    path: /login
    defaults:
        _controller: FrameworkBundle:Redirect:urlRedirect
        path: /app
        permanent: true